# Generated by Django 6.0 on 2026-05-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='identifier',
            field=models.CharField(default='unknown_team', max_length=100),
        ),
    ]
