# Generated by Django 6.0 on 2026-06-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='category',
            field=models.CharField(choices=[('Platinum', 'PLATINUM'), ('Gold', 'GOLD'), ('Silver', 'SILVER'), ('Bronze', 'BRONZE')], default='Bronze', max_length=30),
        ),
    ]
