# Generated by Django 6.0 on 2026-06-14 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('teams', '0004_team_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.team'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='New Player', max_length=100),
        ),
    ]
