# Generated by Django 6.0 on 2026-06-11 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0004_team_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_date', models.DateField()),
                ('winner', models.CharField(blank=True, choices=[('CHALLENGER_TEAM', 'Challenger_Team'), ('CHALLENGED_TEAM', 'Challenged_Team'), ('DRAW', 'Draw')], max_length=20, null=True)),
                ('challenger_points', models.PositiveIntegerField(blank=True, null=True)),
                ('challenged_points', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenged', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges_received', to='teams.team')),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges_initiated', to='teams.team')),
            ],
            options={
                'ordering': ['-challenge_date'],
            },
        ),
    ]
