# Generated by Django 6.0 on 2026-06-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams_challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('TODAY', 'Today'), ('PENDING_RESULT', 'Pending_Result'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=20),
        ),
    ]
